### ISSUE TITLE
Ask community about expected behaviour if Undo/Redo is invoked during "play"

### ISSUE THREAD

**Issue by dforrer** [lxxxvi/three.js#22]
Result: Answer from Community (e.g. Reddit or IRC)

**Comment by lxxxvi** [comment]
Question asked on reddit:
https://www.reddit.com/r/threejs/comments/3j21nx/threejsorg_editor_what_should_happen_if_undo_or/

**Comment by dforrer** [comment]
**Note:** While merging the changes from the master- to the dev-branch I had to remove the calls to signals.stopPlayer from inside History.js because app.js started to throw errors.

**Comment by lxxxvi** [comment]
Undo/Redo disabled during play
