### ISSUE TITLE
TestCase 5 failed: Object in wrong state after 2nd Undo

### ISSUE THREAD

**Issue by lxxxvi** [lxxxvi/three.js#3]
**TC 5**

**Executed** 26.07.2015

**Commit** 94b5d9dc09422eda5200de8f4c5515786a451b57

**Tested with browsers** 
Firefox 39.0
Chrome 44.0.2403.107 

**Execution**
1. Select object {A}
= State 1
2. Modify one property, i.e. x-coordinate
= State 2
3. Undo (Menu: Edit > Undo)
= State 1
4. Modify one property, i.e. y-coordinate
= State 3
5. Undo (Menu: Edit > Undo)

**Result** Object in State 2. Expected is state 1.

**Comment by dforrer** [comment]
The "oldPosition" (=currentPosition) was not updated correctly when an undo happened. Solved by adding a new signal "undoCalled".
