### ISSUE TITLE
Check if Ctrl-Z, Ctrl-Shift-Z conflicts with anything

### ISSUE THREAD

**Issue by dforrer** [lxxxvi/three.js#39]

**Comment by dforrer** [comment]
The changes to [Script.js](https://github.com/lxxxvi/three.js/blob/3a68d62a68a2f0294078fe50bdcf47f21159ed9d/editor/js/Script.js) interfere with the separate undo/redo-history of the editor ([codemirror](https://codemirror.net/doc/manual.html)). By using **codemirror.setValue()** on every change we mess with the history of the editor somehow.

**Comment by dforrer** [comment]
Although Ctrl-Z and Ctrl-Shift-Z conflict with the undo/redo keys of the editor (codemirror) on Windows, they are never executed for both at the same time.

**Comment by lxxxvi** [comment]
Closing the issue.
