### ISSUE TITLE
Chrome steadily updates color (i.e. Pointlight) when using ColorPicker

### ISSUE THREAD

**Issue by lxxxvi** [lxxxvi/three.js#5]
Tested with Chrome: Version 44.0.2403.130 (64-bit)
Commit: 4894e33ce5de58568b27daea6c473a6fe8536402

(Chrome only, Firefox is fine, iEx and Safari not tested)

1. New Scene
2. Add Box
3. Add Pointlight
3. Select Pointlight
4. Click Color (ColorPicker opens...)
5. Click and hold (mousedown) color and dragaround

Expected: Only one history item is written (last color is stored)
Actual: Multiple colors are written (every n-miliseconds)

**Comment by dforrer** [comment]
Fixed in commit f54991ae0d7eeb1d92fad966a49f954c7d7a4a35

CmdSetColor is now updateable.
