### ISSUE TITLE
TestCmdSetColor failed, color value after undo is unexpected

### ISSUE THREAD

**Issue by lxxxvi** [lxxxvi/three.js#7]
Unittest: TestCmdSetColor.js

Commit: 9436f8e86f723e82da122945ce1c96b88e622e19
Testartifact: http://ip5.fukuro.ch/tests/unittest_editor_9436f8e_20150809_165123.html

1. A Pointlight is created (with default color value 54321)
2. Color is set to green through CmdSetColor, assert is fine
3. Color is set to blue through CmdSetColor, assert is fine
4. Color is set to yellow through CmdSetColor, assert is fine
5. Undo 
6. *Color is not blue*, it's the default value 54321 !
7. Redo
8. Color is yellow again, assert is fine!

Because I had a clue, I added a 500ms sleep before undoing (Step 5). Then it works!

Can this be fixed, or do we have to put the 500ms sleep?

**Comment by dforrer** [comment]
Fixed by setting updatable of every command to false. This way we can avoid adding a delay.
Commit 5c610ee9ea972d553f6a4cd79dcef369a648952e
